=== gaul/modernizer-maven-plugin/modernizer-maven-plugin/src/main/resources/modernizer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="modernizer">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="violation" type="violationType"
                    minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="violationType">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="version" type="javaVersionType"/>
      <xs:element name="until" type="javaVersionType" minOccurs="0"/>
      <xs:element name="comment" type="xs:string"/>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="javaVersionType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(1\.)?[0-9]+"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== gaul/modernizer-maven-plugin/modernizer-maven-plugin/src/main/resources/modernizer.xml
<?xml version="1.0"?>
<modernizer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="modernizer.xsd">

  <!--
  This file contains the standard set of violations for Modernizer.  The
  violation names use the same format that javap emits.
  -->

  <violation>
    <name>com/google/common/base/Function</name>
    <version>8</version>
    <comment>Prefer java.util.function.Function</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Predicate</name>
    <version>8</version>
    <comment>Prefer java.util.function.Predicate</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Supplier</name>
    <version>8</version>
    <comment>Prefer java.util.function.Supplier</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.ISO_8859_1:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.ISO_8859_1</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.US_ASCII:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.US_ASCII</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.UTF_8:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.UTF_8</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.UTF_16BE:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.UTF_16BE</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.UTF_16LE:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.UTF_16LE</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Charsets.UTF_16:Ljava/nio/charset/Charset;</name>
    <version>7</version>
    <comment>Prefer java.nio.charset.StandardCharsets.UTF_16</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Objects.equal:(Ljava/lang/Object;Ljava/lang/Object;)Z</name>
    <version>7</version>
    <comment>Prefer java.util.Objects.equals(Object, Object)</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Objects.hashCode:([Ljava/lang/Object;)I</name>
    <version>7</version>
    <comment>Prefer java.util.Objects.hash(Object...)</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Optional.absent:()Lcom/google/common/base/Optional;</name>
    <version>8</version>
    <comment>Prefer java.util.Optional.empty()</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Optional.of:(Ljava/lang/Object;)Lcom/google/common/base/Optional;</name>
    <version>8</version>
    <comment>Prefer java.util.Optional.of(Object)</comment>
  </violation>

  <violation>
    <name>com/google/common/base/Optional.fromNullable:(Ljava/lang/Object;)Lcom/google/common/base/Optional;</name>
    <version>8</version>
    <comment>Prefer java.util.Optional.ofNullable(Object)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.newArrayList:()Ljava/util/ArrayList;</name>
    <version>7</version>
    <comment>Prefer java.util.ArrayList&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.newArrayListWithCapacity:(I)Ljava/util/ArrayList;</name>
    <version>7</version>
    <comment>Prefer java.util.ArrayList&lt;&gt;(int)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.newArrayList:([Ljava/lang/Object;)Ljava/util/ArrayList;</name>
    <version>7</version>
    <comment>Prefer new java.util.ArrayList&lt;&gt;(java.util.Arrays.asList(...))</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.newCopyOnWriteArrayList:()Ljava/util/concurrent/CopyOnWriteArrayList;</name>
    <version>7</version>
    <comment>Prefer java.util.concurrent.CopyOnWriteArrayList&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.newLinkedList:()Ljava/util/LinkedList;</name>
    <version>7</version>
    <comment>Prefer java.util.LinkedList&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Lists.reverse:(Ljava/util/List;)Ljava/util/List;</name>
    <version>21</version>
    <comment>Prefer java.util.List.reversed()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newConcurrentMap:()Ljava/util/concurrent/ConcurrentMap;</name>
    <version>7</version>
    <comment>Prefer java.util.concurrent.ConcurrentHashMap&lt;&gt;() or customize the map using com.google.common.collect.MapMaker</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newEnumMap:(Ljava/lang/Class;)Ljava/util/EnumMap;</name>
    <version>7</version>
    <comment>Prefer java.util.EnumMap&lt;&gt;(Class)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newEnumMap:(Ljava/util/Map;)Ljava/util/EnumMap;</name>
    <version>7</version>
    <comment>Prefer java.util.EnumMap&lt;&gt;(Map)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newHashMap:()Ljava/util/HashMap;</name>
    <version>7</version>
    <comment>Prefer java.util.HashMap&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newHashMap:(Ljava/util/Map;)Ljava/util/HashMap;</name>
    <version>7</version>
    <comment>Prefer java.util.HashMap&lt;&gt;(Map)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newHashMapWithExpectedSize:(I)Ljava/util/HashMap;</name>
    <version>19</version>
    <comment>Prefer java.util.HashMap.newHashMap(int)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newIdentityHashMap:()Ljava/util/IdentityHashMap;</name>
    <version>7</version>
    <comment>Prefer java.util.IdentityHashMap&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newLinkedHashMap:()Ljava/util/LinkedHashMap;</name>
    <version>7</version>
    <comment>Prefer java.util.LinkedHashMap&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newLinkedHashMapWithExpectedSize:(I)Ljava/util/LinkedHashMap;</name>
    <version>19</version>
    <comment>Prefer java.util.LinkedHashMap.newLinkedHashMap(int)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newLinkedHashMap:(Ljava/util/Map;)Ljava/util/LinkedHashMap;</name>
    <version>7</version>
    <comment>Prefer java.util.LinkedHashMap&lt;&gt;(Map)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newTreeMap:()Ljava/util/TreeMap;</name>
    <version>7</version>
    <comment>Prefer java.util.TreeMap&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newTreeMap:(Ljava/util/Comparator;)Ljava/util/TreeMap;</name>
    <version>7</version>
    <comment>Prefer java.util.TreeMap&lt;&gt;(Comparator)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.newTreeMap:(Ljava/util/SortedMap;)Ljava/util/TreeMap;</name>
    <version>7</version>
    <comment>Prefer java.util.TreeMap&lt;&gt;(SortedMap)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.unmodifiableNavigableMap:(Ljava/util/NavigableMap;)Ljava/util/NavigableMap;</name>
    <version>8</version>
    <comment>Prefer java.util.Collections.unmodifiableNavigableMap(NavigableMap)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.synchronizedNavigableMap:(Ljava/util/NavigableMap;)Ljava/util/NavigableMap;</name>
    <version>8</version>
    <comment>Prefer java.util.Collections.synchronizedNavigableMap(NavigableMap)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Maps.immutableEntry:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/Map$Entry;</name>
    <version>9</version>
    <comment>Prefer java.util.Map.entry(Object, Object) which rejects null keys and values</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newConcurrentHashSet:()Ljava/util/Set;</name>
    <version>8</version>
    <comment>Prefer java.util.concurrent.ConcurrentHashMap.newKeySet()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newCopyOnWriteArraySet:()Ljava/util/concurrent/CopyOnWriteArraySet;</name>
    <version>7</version>
    <comment>Prefer java.util.concurrent.CopyOnWriteArraySet&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newHashSet:()Ljava/util/HashSet;</name>
    <version>7</version>
    <comment>Prefer java.util.HashSet&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newHashSetWithExpectedSize:(I)Ljava/util/HashSet;</name>
    <version>19</version>
    <comment>Prefer java.util.HashSet.newHashSet(int)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newLinkedHashSet:()Ljava/util/LinkedHashSet;</name>
    <version>7</version>
    <comment>Prefer java.util.LinkedHashSet&lt;&gt;()</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newLinkedHashSetWithExpectedSize:(I)Ljava/util/LinkedHashSet;</name>
    <version>19</version>
    <comment>Prefer java.util.LinkedHashSet.newLinkedHashSet(int)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newSetFromMap:(Ljava/util/Map;)Ljava/util/Set;</name>
    <version>6</version>
    <comment>Prefer java.util.Collections.newSetFromMap(Map)</comment>
  </violation>

  <violation>
    <name>com/google/common/collect/Sets.newTreeSet:()Ljava/util/TreeSet;</name>
    <version>7</version>
    <comment>Prefer java.util.TreeSet&lt;&gt;()</comment>
  </violation>

  <violation>
